version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init-postgres.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${TARGET}
    container_name: nest_api
    environment:
      PORT: ${API_PORT}
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # app:
  #   build:
  #     context: ..
  #     dockerfile: ./docker-dev/Dockerfile.app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ..:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongo
  #     - scraper
  #     - qdrant

volumes:
  postgres_data: # Define a named volume for data persistence

